# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ml_window_gui.ui'
#
# Created: Thu Mar 25 05:49:49 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #QtGui.QApplication.setStyle(QtQui.QStyleFactory.create('Plastique'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowTitle("__siMukti__")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gambar/vlibkids.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 781, 551))
        self.tabs.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabs.setTabPosition(QtGui.QTabWidget.South)
        self.tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs.setObjectName("tabs")
        self.tab_pengaturan = QtGui.QWidget()
        self.tab_pengaturan.setObjectName("tab_pengaturan")
        self.groupBox = QtGui.QGroupBox(self.tab_pengaturan)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 111))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 281, 20))
        self.lineEdit.setCursor(QtCore.Qt.BlankCursor)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(80, 40, 121, 23))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 40, 131, 23))
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_pengaturan)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 10, 371, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_pengaturan)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 751, 381))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tab_pengaturan_browser_finds = QtGui.QTabWidget(self.groupBox_3)
        self.tab_pengaturan_browser_finds.setGeometry(QtCore.QRect(10, 20, 731, 351))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_pengaturan_browser_finds.sizePolicy().hasHeightForWidth())
        self.tab_pengaturan_browser_finds.setSizePolicy(sizePolicy)
        self.tab_pengaturan_browser_finds.setObjectName("tab_pengaturan_browser_finds")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 731, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tab_pengaturan_browser_finds.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_pengaturan_browser_finds.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tab_pengaturan_browser_finds.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tab_pengaturan_browser_finds.addTab(self.tab_4, "")
        self.tabs.addTab(self.tab_pengaturan, "")
        self.tab_finds = QtGui.QWidget()
        self.tab_finds.setObjectName("tab_finds")
        self.tab_finds_table = QtGui.QTableView(self.tab_finds)
        self.tab_finds_table.setGeometry(QtCore.QRect(10, 20, 751, 371))
        self.tab_finds_table.setObjectName("tab_finds_table")
        self.tab_finds_label_atas = QtGui.QLabel(self.tab_finds)
        self.tab_finds_label_atas.setGeometry(QtCore.QRect(10, 0, 751, 16))
        self.tab_finds_label_atas.setObjectName("tab_finds_label_atas")
        self.tabs.addTab(self.tab_finds, "")
        self.tab_bayes = QtGui.QWidget()
        self.tab_bayes.setObjectName("tab_bayes")
        self.tab_bayessian_label_atas = QtGui.QLabel(self.tab_bayes)
        self.tab_bayessian_label_atas.setGeometry(QtCore.QRect(10, 0, 751, 16))
        self.tab_bayessian_label_atas.setObjectName("tab_bayessian_label_atas")
        self.tab_bayessian_table = QtGui.QTableView(self.tab_bayes)
        self.tab_bayessian_table.setGeometry(QtCore.QRect(10, 20, 751, 371))
        self.tab_bayessian_table.setObjectName("tab_bayessian_table")
        self.tabs.addTab(self.tab_bayes, "")
        self.tab_knn = QtGui.QWidget()
        self.tab_knn.setObjectName("tab_knn")
        self.tabs.addTab(self.tab_knn, "")
        self.tab_neural = QtGui.QWidget()
        self.tab_neural.setObjectName("tab_neural")
        self.tabs.addTab(self.tab_neural, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.menu_info = QtGui.QAction(MainWindow)
        self.menu_info.setObjectName("menu_info")
        self.menu_exit = QtGui.QAction(MainWindow)
        self.menu_exit.setObjectName("menu_exit")
        self.menuMenu.addAction(self.menu_info)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.menu_exit)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.tab_pengaturan_browser_finds.setCurrentIndex(0)
        QtCore.QObject.connect(self.menu_exit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lokasi Data :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Tentukan Lokasi File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Inisialisasi Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Input Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Find-S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Bayessian", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "k-NN", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Neural", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Data Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Sky", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Air Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Humidity", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Wind", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Water", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Forecast", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Enjoy ?", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_pengaturan_browser_finds.setTabText(self.tab_pengaturan_browser_finds.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Data Find-S", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_pengaturan_browser_finds.setTabText(self.tab_pengaturan_browser_finds.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Data Bayessian", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_pengaturan_browser_finds.setTabText(self.tab_pengaturan_browser_finds.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Data k-NN", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_pengaturan_browser_finds.setTabText(self.tab_pengaturan_browser_finds.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Data Neural", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_pengaturan), QtGui.QApplication.translate("MainWindow", "Pengaturan", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_finds_label_atas.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Tampilan hasil algoritma Find-S</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_finds), QtGui.QApplication.translate("MainWindow", "Find-S", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_bayessian_label_atas.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Tampilan hasil algoritma Bayessian</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_bayes), QtGui.QApplication.translate("MainWindow", "Bayessian", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_knn), QtGui.QApplication.translate("MainWindow", "k-NN", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_neural), QtGui.QApplication.translate("MainWindow", "Neural Networks", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_info.setText(QtGui.QApplication.translate("MainWindow", "Info Aplikasi", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_exit.setText(QtGui.QApplication.translate("MainWindow", "Keluar", None, QtGui.QApplication.UnicodeUTF8))
